CREATE OR REPLACE TRIGGER DO_FLIGHT_HISTORY
AFTER INSERT ON FLIGHT
FOR EACH ROW
DECLARE
    message_error varchar2(50);
BEGIN
    message_error := '';
    INSERT INTO FLIGHT_HISTORY VALUES (:NEW.ID, :NEW.BACK_DURATION, :NEW.DEPARTURE, :NEW.DESTINATION, :NEW.DESTINATION_DEPARTURE, :NEW.DURATION, :NEW.ORIGIN);
EXCEPTION
    WHEN OTHERS THEN
        message_error := 'General error';
END;